VALLHALLA_DICT = {
    "mix": range(40, 80),
    "delay_ms": range(10, 1500),
    "delaywarp": range(40, 100),
    "feedback": range(10, 100),
    "density": range(0, 100),
    "width": range(-100, 100),
    "lowcut": range(10, 2000, 10),
    "highcut": range(200, 20000, 15),
    "modrate": [x / 100.0 for x in range(1, 1000, 2)],
    "moddepth": range(0, 100),
    "mode": [
        "Gemini",
        "Hydra",
        "Centaurus",
        "Sagittarius",
        "Great Annihilator",
        "Andromeda",
        "Large Magellanic Cloud",
        "Triangulum",
        "Lyra",
        "Capricorn",
        "Cirrus Major",
        "Cirrus Minor",
        "Cassiopeia",
        "Orion",
        "Aquarius",
        "Pisces",
        "Scorpio",
        "Libra",
        "Leo",
        "Virgo",
        "Pleiades",
        "Sirius",
    ],
}

FULL_RANGES_VALLHALLA_DICT = {
    "mix": range(0, 100),
    "delay_ms": range(0, 2000),
    "delaywarp": range(0, 100),
    "feedback": range(0, 100),
    "density": range(0, 100),
    "width": range(-100, 100),
    "lowcut": range(10, 2000, 10),
    "highcut": range(200, 20000, 15),
    "modrate": [x / 100.0 for x in range(1, 1000, 2)],
    "moddepth": range(0, 100),
    "mode": [
        "Gemini",
        "Hydra",
        "Centaurus",
        "Sagittarius",
        "Great Annihilator",
        "Andromeda",
        "Large Magellanic Cloud",
        "Triangulum",
        "Lyra",
        "Capricorn",
        "Cirrus Major",
        "Cirrus Minor",
        "Cassiopeia",
        "Orion",
        "Aquarius",
        "Pisces",
        "Scorpio",
        "Libra",
        "Leo",
        "Virgo",
        "Pleiades",
        "Sirius",
    ],
}

TAL_REVERB_DICT = {
    "wet": range(20, 80),
    "delay_s": [x / 1000.0 for x in range(0, 1001)],
    "size": range(20, 80),
    # "low_cut_freq": range(0, 30000, 60),
    # "high_cut_freq": range(0, 30000, 60),
    # "peak_freq": range(0, 30000, 60),
    # "peak_amount": [x / 1000 for x in range(-36000, 36000, 75)],
    "modulation_rate": range(20, 80),
    "modulation_depth": range(20, 80),
    "diffuse": range(20, 80),
    "damp": range(20, 80),
    "harmonic_tune": [x * 0.02 for x in range(0, 300)],
    "harmonic_amount": range(0, 20),
}
