VALLHALLA_DICT = {
    "mix": range(0, 100),
    "delay_ms": range(0, 2000),
    "delaywarp": range(0, 100),
    "feedback": range(0, 100),
    "density": range(0, 100),
    "width": range(-100, 100),
    "lowcut": range(10, 2000, 10),
    "highcut": range(200, 20000, 15),
    "modrate": [x / 100.0 for x in range(1, 1000, 2)],
    "moddepth": range(0, 100),
    "mode": [
        "Gemini",
        "Hydra",
        "Centaurus",
        "Sagittarius",
        "Great Annihilator",
        "Andromeda",
        "Large Magellanic Cloud",
        "Triangulum",
        "Lyra",
        "Capricorn",
        "Cirrus Major",
        "Cirrus Minor",
        "Cassiopeia",
        "Orion",
        "Aquarius",
        "Pisces",
        "Scorpio",
        "Libra",
        "Leo",
        "Virgo",
        "Pleiades",
        "Sirius",
    ],
}
