#import "/thesis/utils/todo.typ": TODO

= Conclusion

This thesis set out to investigate state-of-the-art dereverberation models with respect to real-time applicability on diverse audio signals. Toward this goal, a systematic analysis of loss functions and their suitability as indicators of dereverberation performance was conducted, which motivated the development of a custom perceptual quality network for use as a training objective. A task-specific dataset was curated ensuring a wide range of audio classes are covered, for which a diverse set of reverberation methods was implemented, namely @RIR\-based convolution, room simulation, and decay networks. This dataset demonstrated broad applicability, serving as an effective training resource for both the objective quality network and the dereverberation network. Building upon the Conv-TasNet architecture, a novel dereverberation model was subsequently implemented, incorporating both the @SI-SNR and the proposed perceptual and objective quality network as loss functions, and evaluated against established baselines.

Our results show a gap in speech and out-of-domain dereverberation performance in the investigated existing models. StoRM, a frequency-domain model, and Conv-TasNet, a time-domain model, are both able to convincingly dereverberate speech signals but fail at out-of-domain samples such as music. Conv-TasNet demonstrated faster-than-real-time inference, rendering it markedly more computationally efficient than StoRM, for which only near-real-time performance could be achieved on prosumer-grade hardware.

The evaluation of loss functions investigated the @MSE, @MAE, @SI-SNR, @PESQ and @PEAQ metrics as indicators of dereverberation. The @SI-SNR:short is reported as the strongest metric. The perceptual quality network, primarily grounded in the ODG measure, failed to yield satisfactory performance. However, the objective quality network demonstrated good performance surpassing the @SI-SNR across the majority of evaluation conditions.

// Our own implementation of a dereverberation network, utilizing @SI-SNR as a loss function, outperformed StoRM and Conv-TasNet on diverse signals. The same architecture used with the objective quality network as a training objective was unable to generate usable results.
Our own implementation of a dereverberation network, utilizing @SI-SNR, outperformed StoRM and Conv-TasNet on diverse signals. The same architecture used with the objective quality network was unable to generate usable results.
