#import "/thesis/utils/diagram.typ": diagram
== Implementation of Dereverberation Network

#v(0.5cm)
#align(center + horizon, scale(
  130%,
  rotate(90deg, [#box[
      #set text(size: 7pt)
      #diagram(
        table(
          columns: (
            3.3fr,
            0.9fr,
            1.9fr,
            0.8fr,
            0.8fr,
            0.8fr,
            0.8fr,
            1.4fr,
            0.7fr,
            0.8fr,
            0.7fr,
            0.7fr,
            1.2fr,
            1fr,
            0.8fr,
            3.8fr,
          ),
          align: left + top,

          table.header(
            [*Run ID*],
            [*lr*],
            [*loss*],
            [*seg*],
            [*sr*],
            [*N*],
            [*win*],
            [*tcn*],
            [*k*],
            [*drop*],
            [*X*],
            [*R*],
            [*dil*],
            [*causal*],
            [*skip*],
            [*Notes*],
          ),

          [derev_1],
          [1e-3],
          [perceptual],
          [4.0],
          [44100],
          [64],
          [-],
          [[64x5]],
          [4],
          [0.1],
          [0],
          [0],
          [-],
          [true],
          [false],
          [Initial masking baseline],

          [derev_1_increased],
          [1e-4],
          [perceptual],
          [4.0],
          [44100],
          [265],
          [-],
          [-],
          [3],
          [0.0],
          [8],
          [3],
          [-],
          [false],
          [true],
          [Higher-capacity variant],

          [derev_tcn_v1],
          [1e-4],
          [perceptual],
          [2.0],
          [44100],
          [256],
          [-],
          [[128x8]],
          [3],
          [0.1],
          [8],
          [4],
          [1..128],
          [false],
          [true],
          [First tuned TCN],

          [derev_mha_v1],
          [1e-4],
          [perceptual],
          [2.0],
          [44100],
          [-],
          [-],
          [-],
          [-],
          [-],
          [-],
          [-],
          [-],
          [-],
          [-],
          [Attention variant],

          [derev_tcn_v2_AdamW],
          [1e-4],
          [perceptual],
          [2.0],
          [44100],
          [256],
          [-],
          [[128x8]],
          [3],
          [0.1],
          [8],
          [4],
          [1..128],
          [false],
          [true],
          [Optimizer study run],

          [derev_tcn_v2_MSE],
          [1e-4],
          [mse],
          [2.0],
          [44100],
          [256],
          [-],
          [[128x8]],
          [3],
          [0.1],
          [8],
          [4],
          [1..128],
          [false],
          [true],
          [Loss ablation],

          [derev_tcn_v2_Small],
          [1e-4],
          [mse],
          [2.0],
          [44100],
          [256],
          [-],
          [[128x6]],
          [3],
          [0.1],
          [6],
          [4],
          [1..32],
          [false],
          [true],
          [Smaller TCN],

          [derev_tcn_v2_Dropout],
          [1e-4],
          [perceptual],
          [2.0],
          [44100],
          [256],
          [-],
          [[128x8]],
          [3],
          [0.2],
          [8],
          [4],
          [1..128],
          [false],
          [true],
          [Dropout ablation],

          [derev_tcn_v3],
          [1e-4],
          [perceptual],
          [2.0],
          [44100],
          [256],
          [-],
          [[128x8]],
          [3],
          [0.1],
          [8],
          [4],
          [1..128],
          [false],
          [true],
          [v3 baseline],

          [derev_tcn_v3_MSE],
          [1e-4],
          [mse],
          [2.0],
          [44100],
          [256],
          [-],
          [[128x8]],
          [3],
          [0.1],
          [8],
          [4],
          [1..128],
          [false],
          [true],
          [v3 with MSE],

          [derev_convtasnet],
          [1e-4],
          [perceptual],
          [2.0],
          [44100],
          [512],
          [2ms],
          [[512x24]],
          [3],
          [0.0],
          [8],
          [3],
          [1..128x3],
          [false],
          [true],
          [Conv-TasNet-style setting],

          [derev_tcn_v4_SISNR],
          [1e-4],
          [sisnr],
          [4.0],
          [44100],
          [512],
          [2ms],
          [[179x24]],
          [3],
          [0.0],
          [8],
          [3],
          [1..128x3],
          [false],
          [true],
          [v4 with SI-SNR loss],

          [derev_tcn_v4_percep],
          [1e-4],
          [perceptual],
          [4.0],
          [44100],
          [512],
          [2ms],
          [[179x24]],
          [3],
          [0.0],
          [8],
          [3],
          [1..128x3],
          [false],
          [true],
          [v4 with perceptual loss],
        ),
        caption: [All dereverberation hyperparameter configurations. Abbreviations: lr=learning rate, seg=segment length (seconds), N=encoder channels, k=kernel size, drop=dropout, X=num blocks per repeat, R=num repeats, dil=dilation pattern, sr=sample rate skip=skip connections enabled or not, loss=loss function used for training.],
        short-caption: [
          All dereverberation hyperparameter configurations.
        ],
      )<tab_derev_hparams>
    ]
  ]),
))

== Results of Perceptual Quality Network
#diagram(
  caption: [@KDE plots of predicted versus ground truth values of all perceptual quality metrics at epoch 195, with the diagonal indicating perfect agreement.],
  image("/experiments/perceptual-quality/plots/epoch_195-odg-perceptual_net_best.svg"),
)<results_percep_pred_vs_truth>

== Results of Objective Quality Network

#diagram(
  caption: [@KDE plots of predicted versus ground truth values of all objective quality metrics using the updated quality score at epoch 61, with the diagonal indicating perfect agreement.],
  image("/experiments/perceptual-quality/plots/epoch_61-quality-perceptual_net_best.svg"),
)<results_obj_score_pred_vs_truth>

#diagram(
  caption: [@KDE plots of predicted versus ground truth values of all objective quality metrics using the updated quality score and loss at epoch 166, with the diagonal indicating perfect agreement.],
  image("/experiments/perceptual-quality/plots/epoch_166-quality-perceptual_net_best.svg"),
)<results_obj_score_loss_pred_vs_truth>
