[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pesq>=0.0.4",
    "scikit-metrics>=0.1.0",
    "soundfile>=0.13.1",
    "torch>=2.10.0",
    "torchaudio>=2.10.0",
    "torchmetrics>=1.8.2",
    "tqdm>=4.67.3",
]
